const express = require('express')
const cors = require('cors')
const app = express()
const { setupPromise } = require('./models')
const { setupStartingState } = require('./setup.js')
setupPromise.then(() => setupStartingState())
app.use('/assets', express.static('assets'))
app.use(express.static('frontend'))
app.use(express.json())
app.use(cors())
app.use(require('./utils/middleware').tokenExtractor)
app.use('/api/users', require('./controllers/users'))
app.use('/api/login', require('./controllers/login'))
app.use('/api/assets', require('./controllers/assets'))
module.exports = app
